name: deno

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.3.0]

    steps:
      - name: Git Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Lint Deno Module
        run: deno fmt --check

      - name: Test Deno Module
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: deno test --allow-all --unstable --failfast
